apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-volume
  namespace: mysql
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/volume" # Create a directory name volume and give that path of the directory
